# SITE CONFIGURATION
baseurl: ""
url: "https://gabtoschi.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Gabriel Toschi                                   # site's title
description: "game designer, web dev"                   # used by search engines
avatar: assets/img/profile.jpg                          # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: oi! eu sou o Toschi                        # Change Blog header text
header_subtext: eu escrevo umas coisas que talvez você goste!
header_feature_image: assets/img/sobre-splash.jpg
footer_text: >
  Espero que tenha gostado! Powered by <a href="https://pages.github.com/">Github Pages</a>, <a href="https://jekyllrb.com/">Jekyll</a>, <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics: G-TH1PNWMT83                          # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  jogos:
    output: true
    permalink: /:collection/:name
    order:
      - reveillon.md
      - timeheist.md
      - plotfromthestars.md
      - perpetualmotion.md
      - cheapchips.md

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

remote_theme: sylhare/Type-on-Strap                   # If using as a remote_theme in github
